// frontend/src/app/features/landing/components/faq-section.component.ts
import { Component, ChangeDetectionStrategy } from '@angular/core';
import { RouterModule } from '@angular/router';
import { ScrollRevealDirective } from '../../../shared/directives/scroll-reveal.directive';

/**
 * FAQ section component for landing page
 *
 * Displays frequently asked questions about:
 * - Mining as a service concept
 * - Payment structure
 * - GNK tokens
 * - Scaling capabilities
 * - Performance tracking
 */
@Component({
  selector: 'app-faq-section',
  standalone: true,
  imports: [RouterModule, ScrollRevealDirective],
  templateUrl: './faq-section.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class FaqSectionComponent {}

<section id="faq" class="py-16 md:py-24">
  <div class="mx-auto w-full max-w-screen-xl px-4 md:px-12 lg:px-20">
    <!-- Section Header -->
    <div appScrollReveal class="text-center mb-12">
      <span class="inline-flex items-center justify-center rounded-full border border-[#FF4C00]/50 bg-transparent px-4 py-1.5 text-sm font-medium text-white mb-4">
        Frequently Asked Questions
      </span>
      <h2 class="text-2xl md:text-3xl font-bold">What people ask about MineGNK</h2>
    </div>

    <!-- FAQ Items -->
    <div class="max-w-3xl mx-auto space-y-4">
      <div appScrollReveal [revealDelay]="0" class="rounded-xl border border-border bg-card/30 p-6">
        <h3 class="text-lg font-semibold text-foreground mb-3">What is mining as a service?</h3>
        <p class="text-muted-foreground text-sm">
          We provision and manage enterprise-grade GPU servers for you. You pay in fiat and earn GNK tokens while we handle all infrastructure — from capacity check and allocation to go-live.
        </p>
      </div>

      <div appScrollReveal [revealDelay]="50" class="rounded-xl border border-border bg-card/30 p-6">
        <h3 class="text-lg font-semibold text-foreground mb-3">How long does provisioning take?</h3>
        <p class="text-muted-foreground text-sm">
          Provisioning typically completes within days after KYC verification and contract signing. We handle server assignment, software installation, and wallet connection end-to-end.
        </p>
      </div>

      <div appScrollReveal [revealDelay]="100" class="rounded-xl border border-border bg-card/30 p-6">
        <h3 class="text-lg font-semibold text-foreground mb-3">How does billing work?</h3>
        <p class="text-muted-foreground text-sm">
          Payment for the first month is required before server assignment. Monthly invoices are issued at calendar month end. Renew by paying no later than 10 days before contract end.
        </p>
      </div>

      <div appScrollReveal [revealDelay]="150" class="rounded-xl border border-border bg-card/30 p-6">
        <h3 class="text-lg font-semibold text-foreground mb-3">Can I scale my mining operation?</h3>
        <p class="text-muted-foreground text-sm">
          Yes. Upgrade is available anytime (subject to capacity). Downgrade is available once per month. Volume discounts are available from 10+ servers.
        </p>
      </div>

      <div appScrollReveal [revealDelay]="200" class="rounded-xl border border-border bg-card/30 p-6">
        <h3 class="text-lg font-semibold text-foreground mb-3">What support do you provide?</h3>
        <p class="text-muted-foreground text-sm">
          We offer 24/7 infrastructure monitoring with business hours support (CET timezone) for infrastructure issues. Network software updates are applied within 24 hours of release.
        </p>
      </div>

      <div appScrollReveal [revealDelay]="250" class="rounded-xl border border-border bg-card/30 p-6">
        <h3 class="text-lg font-semibold text-foreground mb-3">What happens if there's downtime?</h3>
        <p class="text-muted-foreground text-sm">
          Infrastructure-caused downtime receives credits applied to your next payment or refunded. Note: credits apply to infrastructure downtime only and do not cover missed network rewards.
        </p>
      </div>

      <div appScrollReveal [revealDelay]="300" class="rounded-xl border border-border bg-card/30 p-6">
        <h3 class="text-lg font-semibold text-foreground mb-3">What makes Gonka tokens special?</h3>
        <p class="text-muted-foreground text-sm">
          GNK is designed for AI inference workloads in the Gonka network. Rewards are aligned with real compute supply and demand, making it a sustainable token economy.
        </p>
      </div>
    </div>
  </div>
</section>

<!-- CTA Section -->
<section class="py-16 md:py-24">
  <div class="mx-auto w-full max-w-screen-xl px-4 md:px-12 lg:px-20">
    <div class="text-center max-w-2xl mx-auto">
      <h2 appScrollReveal class="text-2xl md:text-3xl font-bold mb-4">Start mining for the AI future today</h2>
      <p appScrollReveal [revealDelay]="100" class="text-muted-foreground mb-8">
        Join the Gonka network and earn tokens that power tomorrow's AI applications.
        Confirm fit before you pay — review configuration and quote before signing.
      </p>
      <a appScrollReveal [revealDelay]="200" routerLink="/auth/register"
         class="group relative inline-flex items-center gap-2 h-12 px-8 text-base font-semibold rounded-lg bg-white/80 text-zinc-900 hover:bg-white/70 transition-all overflow-hidden">
        <span class="absolute inset-0 bg-gradient-to-r from-transparent via-white/25 to-transparent -translate-x-full group-hover:translate-x-full transition-transform duration-700"></span>
        <span class="relative">Get Started</span>
        <svg class="relative w-5 h-5 group-hover:translate-x-1 transition-transform" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 8l4 4m0 0l-4 4m4-4H3"></path>
        </svg>
      </a>
    </div>
  </div>
</section>

// next-frontend/src/components/landing/FaqSection.tsx
'use client';

import { ScrollReveal } from '@/components/ui/ScrollReveal';

const faqs = [
  {
    question: 'What is mining as a service?',
    answer:
      'We provision and manage enterprise-grade GPU servers for you. You pay in fiat and earn GNK tokens while we handle all infrastructure — from capacity check and allocation to go-live.',
  },
  {
    question: 'How long does provisioning take?',
    answer:
      'Provisioning typically completes within days after KYC verification and contract signing. We handle server assignment, software installation, and wallet connection end-to-end.',
  },
  {
    question: 'How does billing work?',
    answer:
      'Payment for the first month is required before server assignment. Monthly invoices are issued at calendar month end. Renew by paying no later than 10 days before contract end.',
  },
  {
    question: 'Can I scale my mining operation?',
    answer:
      'Yes. Upgrade is available anytime (subject to capacity). Downgrade is available once per month. Volume discounts are available from 10+ servers.',
  },
  {
    question: 'What support do you provide?',
    answer:
      'We offer 24/7 infrastructure monitoring with business hours support (CET timezone) for infrastructure issues. Network software updates are applied within 24 hours of release.',
  },
  {
    question: "What happens if there's downtime?",
    answer:
      'Infrastructure-caused downtime receives credits applied to your next payment or refunded. Note: credits apply to infrastructure downtime only and do not cover missed network rewards.',
  },
  {
    question: 'What makes Gonka tokens special?',
    answer:
      'GNK is designed for AI inference workloads in the Gonka network. Rewards are aligned with real compute supply and demand, making it a sustainable token economy.',
  },
];

export function FaqSection() {
  return (
    <section id="faq" className="py-16 md:py-24">
      <div className="mx-auto w-full max-w-screen-xl px-4 md:px-12 lg:px-20">
        {/* Section Header */}
        <ScrollReveal>
          <div className="text-center mb-12">
            <span className="inline-flex items-center justify-center rounded-full border border-[#FF4C00]/50 bg-transparent px-4 py-1.5 text-sm font-medium text-white mb-4">
              Frequently Asked Questions
            </span>
            <h2 className="text-2xl md:text-3xl font-bold">
              What people ask about MineGNK
            </h2>
          </div>
        </ScrollReveal>

        {/* FAQ Items */}
        <div className="max-w-3xl mx-auto space-y-4">
          {faqs.map((faq, index) => (
            <ScrollReveal key={index} delay={index * 50}>
              <div className="rounded-xl border border-border bg-card/30 p-6">
                <h3 className="text-lg font-semibold text-foreground mb-3">
                  {faq.question}
                </h3>
                <p className="text-muted-foreground text-sm">{faq.answer}</p>
              </div>
            </ScrollReveal>
          ))}
        </div>
      </div>
    </section>
  );
}
