// frontend/src/app/features/landing/components/hero-section.component.ts
import { Component } from '@angular/core';
import { RouterModule } from '@angular/router';
import { ScrollRevealDirective } from '../../../shared/directives/scroll-reveal.directive';

/**
 * Hero section component for landing page
 *
 * Displays the main value proposition with:
 * - Animated badge
 * - Hero headline
 * - Subtitle
 * - CTA button to registration
 */
@Component({
  selector: 'app-hero-section',
  standalone: true,
  imports: [RouterModule, ScrollRevealDirective],
  template: `
    <section id="home" class="pt-24 pb-16 md:pt-32 md:pb-24">
      <div class="mx-auto w-full max-w-screen-xl px-4 md:px-12 lg:px-20">
        <div class="flex flex-col items-center text-center">
          <!-- Badge with animated border light (ball rolling in tube) -->
          <button appScrollReveal class="group relative grid overflow-hidden rounded-full px-4 py-1 shadow-[0_1000px_0_0_hsl(0_0%_20%)_inset] transition-colors duration-200 mb-8">
            <!-- Spark effect - rotating light -->
            <span class="badge-spark"></span>
            <!-- Backdrop - covers inside, leaves border visible -->
            <span class="badge-backdrop"></span>
            <!-- Inner content -->
            <span class="relative z-10 py-0.5 text-sm text-neutral-100 flex items-center justify-center gap-1">
              <span>✨</span>
              GPU Mining as a Service
              <svg class="w-4 h-4 ml-1 transition-transform duration-300 ease-in-out group-hover:translate-x-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path>
              </svg>
            </span>
          </button>

          <!-- Heading -->
          <h1 appScrollReveal [revealDelay]="100" class="text-4xl sm:text-5xl md:text-6xl lg:text-7xl font-bold tracking-tight leading-[1.1] mb-6">
            Rent GPUs to mine
            <span class="bg-gradient-to-r from-[#FF4C00] to-[#FF7A45] bg-clip-text text-transparent"> GNK</span>
          </h1>

          <!-- Subtitle -->
          <p appScrollReveal [revealDelay]="200" class="max-w-2xl text-lg md:text-xl text-muted-foreground mb-10">
            Rent enterprise-grade GPUs to mine cryptocurrency on our network.
            Pay in fiat currency and earn tokens that power the future of AI inference.
          </p>

          <!-- CTA Button -->
          <a appScrollReveal [revealDelay]="300" routerLink="/auth/register"
             class="group relative inline-flex items-center gap-2 h-10 px-6 text-sm font-semibold rounded-lg bg-white/80 text-zinc-900 hover:bg-white/70 transition-all overflow-hidden">
            <span class="absolute inset-0 bg-gradient-to-r from-transparent via-white/25 to-transparent -translate-x-full group-hover:translate-x-full transition-transform duration-700"></span>
            <span class="relative">Start mining</span>
            <svg class="relative w-4 h-4 group-hover:translate-x-1 transition-transform" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 8l4 4m0 0l-4 4m4-4H3"></path>
            </svg>
          </a>
        </div>
      </div>
    </section>
  `
})
export class HeroSectionComponent {}

// next-frontend/src/components/landing/HeroSection.tsx
'use client';

import { useTranslations } from 'next-intl';
import { ScrollReveal } from '@/components/ui/ScrollReveal';
import { useHubspot } from '@/lib/contexts/HubspotContext';

export function HeroSection() {
  const t = useTranslations('hero');
  const { openModal } = useHubspot();

  return (
    <section id="home" className="py-16 md:py-32">
      <div className="mx-auto max-w-xl md:max-w-6xl px-6">
        <div className="grid items-center gap-12 md:grid-cols-2 md:gap-12 lg:grid-cols-5 lg:gap-24">
          {/* Left Column: Text Content */}
          <ScrollReveal className="lg:col-span-2">
            <div className="md:pr-6 lg:pr-0">
              {/* Animated Badge */}
              <button className="group relative grid overflow-hidden rounded-full px-4 py-1 shadow-[0_1000px_0_0_hsl(0_0%_20%)_inset] transition-colors duration-200 mb-6">
                <span className="badge-spark" />
                <span className="badge-backdrop" />
                <span className="relative z-10 py-0.5 text-sm text-neutral-100 flex items-center justify-center gap-1">
                  <span>✨</span>
                  {t('badge')}
                  <svg
                    className="w-4 h-4 ml-1 transition-transform duration-300 ease-in-out group-hover:translate-x-0.5"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M9 5l7 7-7 7"
                    />
                  </svg>
                </span>
              </button>

              {/* Heading */}
              <h1 className="text-4xl font-semibold lg:text-5xl leading-[1.1] mb-6">
                {t('title')}{' '}
                <span className="bg-gradient-to-r from-[#FF4C00] to-[#FF7A45] bg-clip-text text-transparent">
                  {t('titleHighlight')}
                </span>{' '}
                {t('titleSuffix')}
              </h1>

              {/* Subtitle */}
              <p className="text-muted-foreground text-lg">{t('subtitle')}</p>
            </div>

            {/* CTA Button */}
            <ScrollReveal delay={100}>
              <div className="mt-8">
                <button
                  type="button"
                  className="inline-flex items-center gap-2 px-8 py-4 bg-accent hover:bg-accent-hover text-white font-semibold text-lg rounded-lg transition-colors duration-200 shadow-lg shadow-accent/25"
                  onClick={() => openModal()}
                >
                  {t('cta')}
                  <svg
                    className="w-5 h-5"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M17 8l4 4m0 0l-4 4m4-4H3"
                    />
                  </svg>
                </button>
              </div>
            </ScrollReveal>
          </ScrollReveal>

          {/* Right Column: What you get panel */}
          <ScrollReveal delay={150} className="lg:col-span-3">
            <aside className="rounded-2xl border border-border bg-zinc-900/40 p-6 md:p-8">
              {/* Kicker */}
              <div className="text-sm font-semibold uppercase tracking-wide text-accent mb-3">
                {t('panel.kicker')}
              </div>

              {/* Description */}
              <p className="text-muted-foreground text-base leading-relaxed mb-6">
                {t('panel.description')}
              </p>

              {/* Divider */}
              <div className="h-px bg-border mb-6" />

              {/* Three pains card */}
              <div className="rounded-xl border border-border bg-zinc-900/60 p-5 md:p-6">
                <h3 className="text-xl font-semibold text-foreground mb-5">
                  {t('panel.painsTitle')}
                </h3>

                <ul className="space-y-4">
                  <li className="flex items-start gap-3">
                    <span className="mt-1.5 w-2 h-2 rounded-full bg-accent flex-shrink-0" />
                    <p className="text-muted-foreground">
                      <strong className="text-foreground">
                        {t('panel.pains.silence.title')}
                      </strong>{' '}
                      {t('panel.pains.silence.description')}
                    </p>
                  </li>
                  <li className="border-t border-dashed border-border/50 pt-4 flex items-start gap-3">
                    <span className="mt-1.5 w-2 h-2 rounded-full bg-accent flex-shrink-0" />
                    <p className="text-muted-foreground">
                      <strong className="text-foreground">
                        {t('panel.pains.opaque.title')}
                      </strong>{' '}
                      {t('panel.pains.opaque.description')}
                    </p>
                  </li>
                  <li className="border-t border-dashed border-border/50 pt-4 flex items-start gap-3">
                    <span className="mt-1.5 w-2 h-2 rounded-full bg-accent flex-shrink-0" />
                    <p className="text-muted-foreground">
                      <strong className="text-foreground">
                        {t('panel.pains.blind.title')}
                      </strong>{' '}
                      {t('panel.pains.blind.description')}
                    </p>
                  </li>
                </ul>
              </div>
            </aside>
          </ScrollReveal>
        </div>
      </div>
    </section>
  );
}
