// frontend/src/app/features/landing/components/pricing-section.component.ts
import { Component, OnInit, inject, signal, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule, DecimalPipe } from '@angular/common';
import { RouterModule } from '@angular/router';
import { ScrollRevealDirective } from '../../../shared/directives/scroll-reveal.directive';
import { NodesService } from '../../../core/services/nodes.service';
import { PublicPricing } from '../../../core/models/admin.model';
import { GPU_PRICING, GpuPricing, calculateMonthlyPrice } from '../../../core/constants/pricing.constants';
import { HubspotFormModalComponent } from './hubspot-form-modal.component';

interface PricingItem {
  gpuType: string;
  pricePerHour: number | null;
  pricePerMonth: number | null;
  isContactSales: boolean;
  specs: GpuPricing | undefined;
}

@Component({
  selector: 'app-pricing-section',
  standalone: true,
  imports: [CommonModule, RouterModule, ScrollRevealDirective, DecimalPipe, HubspotFormModalComponent],
  templateUrl: './pricing-section.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PricingSectionComponent implements OnInit {
  private readonly nodesService = inject(NodesService);

  protected readonly pricing = signal<PricingItem[]>([]);
  protected readonly loading = signal(true);
  protected readonly isModalOpen = signal(false);
  protected readonly selectedGpuType = signal<string | null>(null);

  public ngOnInit(): void {
    this.loadPricing();
  }

  private loadPricing(): void {
    this.nodesService.getPublicPricing().subscribe({
      next: (data) => {
        if (data && data.length > 0) {
          this.pricing.set(
            data.map((item) => ({
              gpuType: item.gpuType,
              pricePerHour: item.pricePerHour,
              pricePerMonth: calculateMonthlyPrice(item.pricePerHour),
              isContactSales: item.isContactSales,
              specs: this.getGpuSpecs(item.gpuType),
            }))
          );
        } else {
          this.useFallbackPricing();
        }
        this.loading.set(false);
      },
      error: () => {
        this.useFallbackPricing();
        this.loading.set(false);
      },
    });
  }

  private useFallbackPricing(): void {
    this.pricing.set(
      GPU_PRICING.map((g) => ({
        gpuType: g.id,
        pricePerHour: g.pricePerHour,
        pricePerMonth: calculateMonthlyPrice(g.pricePerHour),
        isContactSales: g.pricePerHour === null,
        specs: g,
      }))
    );
  }

  private getGpuSpecs(gpuType: string): GpuPricing | undefined {
    return GPU_PRICING.find((g) => g.id === gpuType);
  }

  protected openModal(gpuType: string): void {
    this.selectedGpuType.set(gpuType);
    this.isModalOpen.set(true);
  }

  protected closeModal(): void {
    this.isModalOpen.set(false);
    this.selectedGpuType.set(null);
  }

  protected onFormSubmitted(): void {
    setTimeout(() => this.closeModal(), 3000);
  }
}

<section id="pricing" class="py-16 md:py-24">
  <div class="mx-auto w-full max-w-screen-xl px-4 md:px-12 lg:px-20">
    <!-- Section Header -->
    <div appScrollReveal class="text-center mb-12">
      <span class="inline-flex items-center justify-center rounded-full border border-[#FF4C00]/50 bg-transparent px-4 py-1.5 text-sm font-medium text-white mb-4">
        Simple Pricing
      </span>
      <h2 class="text-2xl md:text-3xl font-bold mb-4">Choose your 8x GPU server package</h2>
      <p class="text-muted-foreground max-w-2xl mx-auto">
        All packages include managed infrastructure, 24/7 monitoring, and month-to-month contracts. No setup fees or long-term commitment.
      </p>
    </div>

    <!-- Pricing Cards -->
    @if (!loading()) {
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        @for (item of pricing(); track item.gpuType; let i = $index) {
          <div appScrollReveal [revealDelay]="i * 75" class="rounded-xl border border-border bg-card/30 p-6 flex flex-col">
            <div class="mb-6">
              <h3 class="text-xl font-bold text-foreground mb-2">{{ item.specs?.name || item.gpuType }}</h3>
              <p class="text-sm text-muted-foreground">{{ item.specs?.description || 'High-performance GPU server' }}</p>
            </div>
            <ul class="space-y-3 mb-6 flex-1">
              @for (feature of item.specs?.features || []; track feature) {
                <li class="flex items-center gap-2 text-sm text-muted-foreground">
                  <svg class="w-4 h-4 flex-shrink-0 text-accent" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path>
                  </svg>
                  {{ feature }}
                </li>
              }
            </ul>
            <div class="mb-6">
              @if (item.isContactSales || item.pricePerHour === null) {
                <span class="text-xl font-bold text-foreground">Custom pricing</span>
              } @else {
                <div class="flex flex-col">
                  <div>
                    <span class="text-3xl font-bold text-foreground">${{ item.pricePerHour | number:'1.2-2' }}</span>
                    <span class="text-muted-foreground text-sm"> /GPU/hour</span>
                  </div>
                  @if (item.pricePerMonth) {
                    <span class="text-sm text-muted-foreground mt-1">${{ item.pricePerMonth | number:'1.0-0' }}/month</span>
                  }
                </div>
              }
            </div>

            <!-- Rent GPU Button -->
            <button
              type="button"
              class="w-full py-3 px-4 bg-[#FF4C00] hover:bg-[#e64500] text-white font-semibold text-sm rounded-lg transition-colors duration-200"
              (click)="openModal(item.specs?.name || item.gpuType)"
            >
              @if (item.isContactSales || item.pricePerHour === null) {
                Contact Sales
              } @else {
                Rent GPU
              }
            </button>
          </div>
        }
      </div>

      <!-- Volume Discount Note -->
      <div appScrollReveal [revealDelay]="400" class="mt-8 text-center">
        <p class="text-sm text-muted-foreground">
          <span class="text-[#FF4C00] font-medium">Volume discounts available</span> from 10+ servers. Contact us for custom pricing.
        </p>
      </div>
    } @else {
      <!-- Loading skeleton -->
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        @for (i of [1, 2, 3, 4]; track i) {
          <div class="rounded-xl border border-border bg-card/30 p-6 animate-pulse">
            <div class="h-6 bg-gray-700 rounded w-1/2 mb-4"></div>
            <div class="h-4 bg-gray-700 rounded w-3/4 mb-6"></div>
            <div class="space-y-3 mb-6">
              @for (j of [1, 2, 3, 4, 5]; track j) {
                <div class="h-4 bg-gray-700 rounded w-full"></div>
              }
            </div>
            <div class="h-8 bg-gray-700 rounded w-1/2 mb-6"></div>
            <div class="h-10 bg-gray-700 rounded"></div>
          </div>
        }
      </div>
    }
  </div>
</section>

<!-- HubSpot Form Modal -->
<app-hubspot-form-modal
  [isOpen]="isModalOpen()"
  [gpuType]="selectedGpuType()"
  (close)="closeModal()"
  (formSubmitted)="onFormSubmitted()"
/>

// next-frontend/src/components/landing/PricingSection.tsx
'use client';

import { ScrollReveal } from '@/components/ui/ScrollReveal';
import { CheckIcon } from '@/components/icons';
import { pricing, formatPrice, formatMonthlyPrice } from '@/data/pricing';
import { useHubspot } from '@/lib/contexts/HubspotContext';

export function PricingSection() {
  const { openModal } = useHubspot();

  return (
    <section id="pricing" className="py-16 md:py-24">
      <div className="mx-auto w-full max-w-screen-xl px-4 md:px-12 lg:px-20">
        {/* Section Header */}
        <ScrollReveal>
          <div className="text-center mb-12">
            <span className="inline-flex items-center justify-center rounded-full border border-[#FF4C00]/50 bg-transparent px-4 py-1.5 text-sm font-medium text-white mb-4">
              Simple Pricing
            </span>
            <h2 className="text-2xl md:text-3xl font-bold mb-4">
              Choose your 8x GPU server package
            </h2>
            <p className="text-muted-foreground max-w-2xl mx-auto">
              All packages include managed infrastructure, 24/7 monitoring, and
              month-to-month contracts. No setup fees or long-term commitment.
            </p>
          </div>
        </ScrollReveal>

        {/* Pricing Cards */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          {pricing.map((item, index) => (
            <ScrollReveal key={item.name} delay={index * 75}>
              <div className="rounded-xl border border-border bg-card/30 p-6 flex flex-col h-full">
                <div className="mb-6">
                  <h3 className="text-xl font-bold text-foreground mb-2">
                    {item.name}
                  </h3>
                  <p className="text-sm text-muted-foreground">
                    {item.description}
                  </p>
                </div>
                <ul className="space-y-3 mb-6 flex-1">
                  {item.features.map((feature) => (
                    <li
                      key={feature}
                      className="flex items-center gap-2 text-sm text-muted-foreground"
                    >
                      <CheckIcon className="w-4 h-4 flex-shrink-0 text-accent" />
                      {feature}
                    </li>
                  ))}
                </ul>
                <div className="mb-6">
                  {item.isContactSales || item.pricePerHour === null ? (
                    <span className="text-xl font-bold text-foreground">
                      Custom pricing
                    </span>
                  ) : (
                    <div className="flex flex-col">
                      <div>
                        <span className="text-3xl font-bold text-foreground">
                          ${formatPrice(item.pricePerHour)}
                        </span>
                        <span className="text-muted-foreground text-sm">
                          {' '}
                          /GPU/hour
                        </span>
                      </div>
                      {item.pricePerMonth && (
                        <span className="text-sm text-muted-foreground mt-1">
                          ${formatMonthlyPrice(item.pricePerMonth)}/month
                        </span>
                      )}
                    </div>
                  )}
                </div>

                {/* Rent GPU Button */}
                <button
                  type="button"
                  className="w-full py-3 px-4 bg-[#FF4C00] hover:bg-[#e64500] text-white font-semibold text-sm rounded-lg transition-colors duration-200"
                  onClick={() => openModal(item.name)}
                >
                  {item.isContactSales || item.pricePerHour === null
                    ? 'Contact Sales'
                    : 'Rent GPU'}
                </button>
              </div>
            </ScrollReveal>
          ))}
        </div>

        {/* Volume Discount Note */}
        <ScrollReveal delay={400}>
          <div className="mt-8 text-center">
            <p className="text-sm text-muted-foreground">
              <span className="text-[#FF4C00] font-medium">
                Volume discounts available
              </span>{' '}
              from 10+ servers. Contact us for custom pricing.
            </p>
          </div>
        </ScrollReveal>
      </div>
    </section>
  );
}
